# Generated by Django 2.1.2 on 2018-11-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_news_order_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['order_sort'], 'verbose_name': '4.News', 'verbose_name_plural': '4.News'},
        ),
        migrations.AddField(
            model_name='consultation',
            name='file',
            field=models.FileField(default='', upload_to='file/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_desc',
            field=models.TextField(verbose_name='Full description'),
        ),
    ]
